version: '3.7'
services:
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres:14.6-alpine
    networks:
      - database
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=languages
    container_name: postgres_db
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    networks:
      - webapp
      - database
    ports:
      - 5500:5500
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/languages
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    depends_on:
      - postgres_db
    restart: always
    command: ['nodemon']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env
    networks:
      - webapp
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - 3000:3000
    command: npm start
    stdin_open: true
    restart: always
    container_name: client

volumes:
  docker-nest-postgres:

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
