version: '3'
services:
  #############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - postgres_db
    environment:
      - SECRET='¯\_(ツ)_/¯'
    restart: always
    command: ['--', 'node', 'main.js']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 80:80
    restart: always
    container_name: client
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres:14.6-alpine
    networks:
      - database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=languages
    restart: always
    container_name: postgres_db
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
