const VIEWBOX_WIDTH = 100;
const VIEWBOX_HEIGHT = 100;
const HALF_VIEWBOX_WIDTH = VIEWBOX_WIDTH / 2;
const HALF_VIEWBOX_HEIGHT = VIEWBOX_HEIGHT / 2;

export {
  VIEWBOX_WIDTH,
  VIEWBOX_HEIGHT,
  HALF_VIEWBOX_WIDTH,
  HALF_VIEWBOX_HEIGHT
};
